/*
 * Producto.java
 *
 * Generated with Matisse Schema Definition Language 9.1.12
 * Generation date: Sun Feb 09 22:49:15 2020
 */

// Note: the package and extends declarations are generated by mt_sdl, do not modify them

package market;

import com.matisse.reflect.*;

/**
 * <code>Producto</code> is a schema class generated by <code>mt_sdl</code>.
 * Any user-written classes will be found at the end of the file, after
 * the '// END of Matisse SDL Generated Code' comment.
 * Attribute types, default values, and relationship minimum and maximum
 * cardinality are stored in the database itself, not in this source code.
 * For more information, see <i>Getting Started with MATISSE</i>.
 */
public class Producto extends com.matisse.reflect.MtObject {

    // BEGIN Matisse SDL Generated Code
    // DO NOT MODIFY UNTIL THE 'END of Matisse SDL Generated Code' MARK BELOW
    /*
     * Generated with Matisse Schema Definition Language 9.1.12
     * Generation Date: Sun Feb 09 22:49:15 2020
     */

    /*
     * Class variables and methods
     */

    /** Class <code>Producto</code> cache ID */
    private static int CID = com.matisse.MtDatabase.allocCID(new com.matisse.reflect.MtClass.Loader("market.Producto"));

    /**
     * Gets the <code>Producto</code> class descriptor.
     * This method supports advanced MATISSE programming techniques such as
     * dynamically modifying the schema.
     * @param db a database
     * @return a class descriptor
     */
    public static com.matisse.reflect.MtClass getClass(com.matisse.MtDatabase db) {
        return (com.matisse.reflect.MtClass)db.getCachedObject(CID);
    }

    /**
     * Factory constructor. This constructor is called by <code>MtObjectFactory</code>.
     * It is public for technical reasons but is not intended to be called
     * directly by user methods.
     * @param db a database
     * @param mtOid an existing object ID in the database
     */
    public Producto(com.matisse.MtDatabase db, int mtOid)  {
        super(db, mtOid);
    }

    /**
     * Cascaded constructor, used by subclasses to create a new object in the database.
     * It is protected for technical reasons but is not intended to be called
     * directly by user methods.
     * @param mtCls a class descriptor (the class to instantiate)
     */
    protected Producto(com.matisse.reflect.MtClass mtCls)  {
        super(mtCls);
    }

    /**
     * Opens an iterator on all instances of this class (and its subclasses).
     * @param <E> a MtObject class     * @param db a database
     * @return an object iterator
     */
    public static <E extends com.matisse.reflect.MtObject> com.matisse.MtObjectIterator<E> instanceIterator(com.matisse.MtDatabase db) {
        return getClass(db).<E>instanceIterator(Producto.class);
    }

    /**
     * Opens an iterator on all instances of this class (and its subclasses).
     * @param <E> a MtObject class     * @param db a database
     * @param numObjPerBuffer maximum number of objects to fetch from the server at a time
     * @return an object iterator
     */
    public static <E extends com.matisse.reflect.MtObject> com.matisse.MtObjectIterator<E> instanceIterator(com.matisse.MtDatabase db, int numObjPerBuffer) {
        return getClass(db).<E>instanceIterator(numObjPerBuffer, Producto.class);
    }

    /**
     * Counts the number of instances of this class (and its subclasses).
     * @param db a database
     * @return total number of instances
     */
    public static long getInstanceNumber(com.matisse.MtDatabase db) {
        return getClass(db).getInstanceNumber();
    }

    /**
     * Opens an iterator on all own instances of this class (excluding subclasses).
     * @param <E> a MtObject class     * @param db a database
     * @return an object iterator
     */
    public static <E extends com.matisse.reflect.MtObject> com.matisse.MtObjectIterator<E> ownInstanceIterator(com.matisse.MtDatabase db) {
        return getClass(db).<E>ownInstanceIterator(Producto.class);
    }

    /**
     * Opens an iterator on all own instances of this class (excluding subclasses).
     * @param <E> a MtObject class     * @param db a database
     * @param numObjPerBuffer maximum number of objects to fetch from the server at a time
     * @return an object iterator
     */
    public static <E extends com.matisse.reflect.MtObject> com.matisse.MtObjectIterator<E> ownInstanceIterator(com.matisse.MtDatabase db, int numObjPerBuffer) {
        return getClass(db).<E>ownInstanceIterator(numObjPerBuffer, Producto.class);
    }

    /**
     * Counts the number of own instances of this class (excluding subclasses).
     * @param db a database
     * @return total number of instances
     */
    public static long getOwnInstanceNumber(com.matisse.MtDatabase db) {
        return getClass(db).getOwnInstanceNumber();
    }

    /*
     * Attribute access methods
     */

    /* Attribute 'nombreProducto' */

    /** Attribute <code>nombreProducto</code> cache ID */
    private static int nombreProductoCID = com.matisse.MtDatabase.allocCID(new com.matisse.reflect.MtAttribute.Loader("nombreProducto",CID));

    /**
     * Gets the <code>nombreProducto</code> attribute descriptor.
     * This method supports advanced MATISSE programming techniques such as
     * dynamically modifying the schema.
     * @param db the database containing the attribute
     * @return the attribute descriptor object
     */
    public static com.matisse.reflect.MtAttribute getNombreProductoAttribute(com.matisse.MtDatabase db) {
        return (com.matisse.reflect.MtAttribute)db.getCachedObject(nombreProductoCID);
    }


    /**
     * Gets the <code>nombreProducto</code> attribute value.
     * @return the value
     *
     * @see #setNombreProducto
     * @see #removeNombreProducto
     */
    public final String getNombreProducto() {
        return getString(getNombreProductoAttribute(getMtDatabase()));
    }

    /**
     * Sets the <code>nombreProducto</code> attribute value.
     * @param val the new value
     *
     * @see #getNombreProducto
     * @see #removeNombreProducto
     */
    public final void setNombreProducto(String val) {
        setString(getNombreProductoAttribute(getMtDatabase()), val);
    }

    /**
     * Removes the current <code>nombreProducto</code> attribute value.
     * Falls back to the default value is there is one.  If the attribute
     * has no default value, it must be set to a new value before commit.
     *
     * @see #getNombreProducto
     * @see #setNombreProducto
     */
    public final void removeNombreProducto() {
        removeValue(getNombreProductoAttribute(getMtDatabase()));
    }

    /**
     * Check if nullable attribute value is set to MT_NULL.
     * @return true if null value
     *
     * @see #getNombreProducto
     * @see #setNombreProducto
     */
    public final boolean isNombreProductoNull() {
        return isNull(getNombreProductoAttribute(getMtDatabase()));
    }

    /**
     * Check if attribute value is set to its default value.
     * @return true if default value
     *
     * @see #getNombreProducto
     * @see #setNombreProducto
     */
    public final boolean isNombreProductoDefaultValue() {
        return isDefaultValue(getNombreProductoAttribute(getMtDatabase()));
    }


    /* Attribute 'fechaEntregaProducto' */

    /** Attribute <code>fechaEntregaProducto</code> cache ID */
    private static int fechaEntregaProductoCID = com.matisse.MtDatabase.allocCID(new com.matisse.reflect.MtAttribute.Loader("fechaEntregaProducto",CID));

    /**
     * Gets the <code>fechaEntregaProducto</code> attribute descriptor.
     * This method supports advanced MATISSE programming techniques such as
     * dynamically modifying the schema.
     * @param db the database containing the attribute
     * @return the attribute descriptor object
     */
    public static com.matisse.reflect.MtAttribute getFechaEntregaProductoAttribute(com.matisse.MtDatabase db) {
        return (com.matisse.reflect.MtAttribute)db.getCachedObject(fechaEntregaProductoCID);
    }


    /**
     * Gets the <code>fechaEntregaProducto</code> attribute value.
     * @return the value
     *
     * @see #setFechaEntregaProducto
     * @see #removeFechaEntregaProducto
     */
    public final String getFechaEntregaProducto() {
        return getString(getFechaEntregaProductoAttribute(getMtDatabase()));
    }

    /**
     * Sets the <code>fechaEntregaProducto</code> attribute value.
     * @param val the new value
     *
     * @see #getFechaEntregaProducto
     * @see #removeFechaEntregaProducto
     */
    public final void setFechaEntregaProducto(String val) {
        setString(getFechaEntregaProductoAttribute(getMtDatabase()), val);
    }

    /**
     * Removes the current <code>fechaEntregaProducto</code> attribute value.
     * Falls back to the default value is there is one.  If the attribute
     * has no default value, it must be set to a new value before commit.
     *
     * @see #getFechaEntregaProducto
     * @see #setFechaEntregaProducto
     */
    public final void removeFechaEntregaProducto() {
        removeValue(getFechaEntregaProductoAttribute(getMtDatabase()));
    }

    /**
     * Check if nullable attribute value is set to MT_NULL.
     * @return true if null value
     *
     * @see #getFechaEntregaProducto
     * @see #setFechaEntregaProducto
     */
    public final boolean isFechaEntregaProductoNull() {
        return isNull(getFechaEntregaProductoAttribute(getMtDatabase()));
    }

    /**
     * Check if attribute value is set to its default value.
     * @return true if default value
     *
     * @see #getFechaEntregaProducto
     * @see #setFechaEntregaProducto
     */
    public final boolean isFechaEntregaProductoDefaultValue() {
        return isDefaultValue(getFechaEntregaProductoAttribute(getMtDatabase()));
    }


    /*
     * Relationship access methods
     */

    /* Relationship 'desarrollado_por' */

    /** Relationship <code>desarrollado_por</code> cache ID */
    private static int desarrollado_porCID = com.matisse.MtDatabase.allocCID(new com.matisse.reflect.MtRelationship.Loader("desarrollado_por",CID));

    /**
     * Gets the <code>desarrollado_por</code> relationship descriptor.
     * This method supports advanced MATISSE programming techniques such as
     * dynamically modifying the schema.
     * @param db a database
     * @return a relationship descriptor object
     */
    public static com.matisse.reflect.MtRelationship getDesarrollado_porRelationship(com.matisse.MtDatabase db) {
        return (com.matisse.reflect.MtRelationship)db.getCachedObject(desarrollado_porCID);
    }

    /**
     * Gets the <code>desarrollado_por</code> relationship's successors.
     * @return an array of objects
     *
     * @see #getDesarrollado_porSize
     * @see #desarrollado_porIterator
     * @see #setDesarrollado_por
     * @see #removeDesarrollado_por
     */
    public final market.Empresa[] getDesarrollado_por() {
        return (market.Empresa[])getSuccessors(getDesarrollado_porRelationship(getMtDatabase()), market.Empresa.class);
    }

    /**
     * Counts the <code>desarrollado_por</code> relationship's successors.
     * @return the number of successors
     *
     * @see #getDesarrollado_por
     * @see #desarrollado_porIterator
     * @see #setDesarrollado_por
     * @see #removeDesarrollado_por
     */
    public final int getDesarrollado_porSize() {
        return getSuccessorSize(getDesarrollado_porRelationship(getMtDatabase()));
    }

    /**
     * Opens an iterator on the <code>desarrollado_por</code> relationship's successors.
     * @param <E> a MtObject class     * @return an object iterator
     *
     * @see #getDesarrollado_por
     * @see #getDesarrollado_porSize
     * @see #setDesarrollado_por
     * @see #removeDesarrollado_por
     */
    public final <E extends com.matisse.reflect.MtObject> com.matisse.MtObjectIterator<E> desarrollado_porIterator() {
        return this.<E>successorIterator(getDesarrollado_porRelationship(getMtDatabase()), market.Empresa.class);
    }

    /**
     * Sets the <code>desarrollado_por</code> relationship's successors.
     * @param succs an array of objects
     *
     * @see #getDesarrollado_por
     * @see #getDesarrollado_porSize
     * @see #desarrollado_porIterator
     * @see #removeDesarrollado_por
     */
    public final void setDesarrollado_por(market.Empresa[] succs) {
        setSuccessors(getDesarrollado_porRelationship(getMtDatabase()), succs);
    }

    /**
     * Inserts one object at the beginning of the existing <code>desarrollado_por</code> successors list.
     * @param succ the object to add
     *
     * @see #getDesarrollado_por
     * @see #getDesarrollado_porSize
     * @see #desarrollado_porIterator
     * @see #setDesarrollado_por
     * @see #removeDesarrollado_por
     */
    public final void prependDesarrollado_por(market.Empresa succ) {
        prependSuccessor(getDesarrollado_porRelationship(getMtDatabase()), succ);
    }

    /**
     * Adds one object to the end of the existing <code>desarrollado_por</code> successors list.
     * @param succ the object to add
     *
     * @see #getDesarrollado_por
     * @see #setDesarrollado_por
     * @see #removeDesarrollado_por
     * @see #getDesarrollado_porSize
     * @see #desarrollado_porIterator
     */
    public final void appendDesarrollado_por(market.Empresa succ) {
        appendSuccessor(getDesarrollado_porRelationship(getMtDatabase()), succ);
    }
    /** Adds multiple objects to the end of the existing <code>desarrollado_por</code> successors list.
     * @param succs an array of objects to add
     *
     * @see #getDesarrollado_por
     * @see #setDesarrollado_por
     * @see #removeDesarrollado_por
     * @see #getDesarrollado_porSize
     * @see #desarrollado_porIterator
     */
    public final void appendDesarrollado_por(market.Empresa[] succs) {
        addSuccessors(getDesarrollado_porRelationship(getMtDatabase()), succs);
    }

    /**
     * Removes objects from the <code>desarrollado_por</code> successors list.
     * @param succs an array of objects to remove
     *
     * @see #getDesarrollado_por
     * @see #setDesarrollado_por
     * @see #getDesarrollado_porSize
     * @see #desarrollado_porIterator
     */
    public void removeDesarrollado_por(market.Empresa[] succs) {
        removeSuccessors(getDesarrollado_porRelationship(getMtDatabase()), succs);
    }

    /**
     * Removes one object from the <code>desarrollado_por</code> successors list.
     * @param succ the object to remove
     *
     * @see #getDesarrollado_por
     * @see #setDesarrollado_por
     * @see #getDesarrollado_porSize
     * @see #desarrollado_porIterator
     */
    public void removeDesarrollado_por(market.Empresa succ) {
        removeSuccessor(getDesarrollado_porRelationship(getMtDatabase()), succ);
    }

    /**
     * Removes all <code>desarrollado_por</code> successors.  When the minimum cardinality
     * is 1, a new successor must be set before commit.
     */
    public final void clearDesarrollado_por() {
        clearSuccessors(getDesarrollado_porRelationship(getMtDatabase()));
    }


    // END of Matisse SDL Generated Code

    /*
     * You may add your own code here...
     */

    /**
     * Default constructor provided as an example.
     * You may delete this constructor or modify it to suit your needs. If you
     * modify it, please revise this comment accordingly.
     * @param db a database
     */
    public Producto(com.matisse.MtDatabase db) {
        super(getClass(db));
    }

    /**
     * Example of <code>toString</code> method.
     * You may delete this method or modify it to suit your needs. If you
     * modify it, please revise this comment accordingly.
     * @return a string
     */
    public java.lang.String toString() {
        return super.toString() + "[Producto]";
    }
}
